### ISSUE TITLE
大佬能不能帮忙编译一下捐赠版本的sharepoint

### ISSUE THREAD

**Issue by dudt** [moeYuiYui/Cloudreve#4]
~~实在的不会呀

**Comment by AishaFisher** [comment]
一样的编译。一样的改个代码

**Comment by dudt** [comment]
> 一样的编译。一样的改个代码

![image](https://user-images.githubusercontent.com/19968269/96989410-3676e900-1558-11eb-9e61-b4b0cace812f.png)
大佬帮忙看一下构建会报这个错误

**Comment by AishaFisher** [comment]
依赖没装好？看看这个package.json的 "monaco-editor-webpack-plugin": "^1.9.0"。或者把node_modules删了重新安装试试
没用过pro版本，或许你问作者更有效。
