### ISSUE TITLE
依赖没装好？看看这个package.json的 "monaco-editor-webpack-plugin": "^1.9.0"。或者把node_modules删了重新安装试试

### ISSUE THREAD

**Issue by dudt** [moeYuiYui/Cloudreve#5]
依赖没装好？看看这个package.json的 "monaco-editor-webpack-plugin": "^1.9.0"。或者把node_modules删了重新安装试试
没用过pro版本，或许你问作者更有效。

_Originally posted by @AishaFisher in https://github.com/moeYuiYui/Cloudreve/issues/4#issuecomment-715904608_

这个我设置了2.0版本还是报错..可以留个联系方式吗？作者天天不管事。。。

**Comment by AishaFisher** [comment]
email: KrySenven@outlook.com
